### ISSUE TITLE
concurrent map iteration and map write

### ISSUE THREAD

**Issue by caarlos0** [charmbracelet/soft-serve#294]
got this in an instance running for a while:

```
fatal error: concurrent map iteration and map write
goroutine 324592 [running]:
github.com/charmbracelet/soft-serve/internal/sync.(*WorkPool).Run(0xc0000c2280)
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/internal/sync/workqueue.go:55 +0x76
github.com/charmbracelet/soft-serve/server.(*Server).mirrorJob.func1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/jobs.go:59 +0x426
github.com/robfig/cron/v3.FuncJob.Run(0x0?)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
goroutine 1 [chan receive, 640 minutes]:
main.glob..func6(0x1bfbb00, {0x1c595f8?, 0x0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/cmd/soft/serve.go:61 +0x606
github.com/spf13/cobra.(*Command).execute(0x1bfbb00, {0x1c595f8, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1bfb540)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/cmd/soft/root.go:64 +0x192
goroutine 37 [select, 640 minutes]:
database/sql.(*DB).connectionOpener(0xc00015f1e0, {0x145fbf8, 0xc000101720})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d
goroutine 22 [IO wait, 640 minutes]:
internal/poll.runtime_pollWait(0x7f5b8b400668, 0x72)
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000116080?, 0xc0003a6ce8?, 0x0)
	/opt/hostedtoolcache/go/1.20.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000116080)
	/opt/hostedtoolcache/go/1.20.4/x64/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc000116080)
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0004c6030)
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc0004c6030)
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/tcpsock.go:297 +0x3d
net/http.(*Server).Serve(0xc0002e12c0, {0x145f320, 0xc0004c6030})
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:3059 +0x385
net/http.(*Server).ListenAndServe(0xc0002e12c0)
	/opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:2988 +0x7d
github.com/charmbracelet/soft-serve/server/web.(*HTTPServer).ListenAndServe(0xc0001b0701?)
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/web/http.go:137 +0x5a
github.com/charmbracelet/soft-serve/server.start.func1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/server.go:93 +0x29
created by github.com/charmbracelet/soft-serve/server.start
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/server.go:92 +0xaa
goroutine 49 [semacquire, 640 minutes]:
sync.runtime_Semacquire(0xc000083a00?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0004bc001?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/sync/waitgroup.go:116 +0x4b
golang.org/x/sync/errgroup.(*Group).Wait(0xc0004ce000)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:53 +0x27
github.com/charmbracelet/soft-serve/server.(*Server).Start(0xc000304f60)
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/server.go:139 +0x288
main.glob..func6.1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/cmd/soft/serve.go:57 +0x85
created by main.glob..func6
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/cmd/soft/serve.go:54 +0x56c
goroutine 65 [select, 640 minutes]:
github.com/charmbracelet/soft-serve/server.start({0x145fbf8, 0xc0004bc000}, 0xc0003b4130)
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/server.go:96 +0x109
github.com/charmbracelet/soft-serve/server.(*Server).Start.func1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/server.go:109 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa5
goroutine 66 [select, 640 minutes]:
github.com/charmbracelet/soft-serve/server.start({0x145fbf8, 0xc0004bc000}, 0xc00033a120)
	/home/runner/go/pkg/mod/github.com/charmbracelet/soft-serve@v0.5.3/server/server.go:96 +0x109
```

I don't know how to reproduce it, though...

**Comment by aymanbagabas** [comment]
Fixed in https://github.com/charmbracelet/soft-serve/commit/a9e4824691f12a7c1e03161e9d60425a2d5ca637

**Comment by caarlos0** [comment]
ah cool, thanks!
